document.writeln("			<footer class=\'ftco-footer ftco-bg-dark ftco-section\'>");
document.writeln("				<div class=\'container px-md-5\'>");
document.writeln("					<div class=\'row mb-5\'>");
document.writeln("						<div class=\'col-md\'>");
document.writeln("							<div class=\'ftco-footer-widget mb-4 ml-md-4\'>");
document.writeln("								<h2 class=\'ftco-heading-2\'>Recent Photos</h2>");
document.writeln("								<ul class=\'list-unstyled photo\'>");
document.writeln("									<li><a href=\'#\' class=\'img\' style=\'background-image: url(../../images/image_1.jpg);\'></a>");
document.writeln("									</li>");
document.writeln("									<li><a href=\'#\' class=\'img\' style=\'background-image: url(../../images/image_2.jpg);\'></a>");
document.writeln("									</li>");
document.writeln("									<li><a href=\'#\' class=\'img\' style=\'background-image: url(../../images/image_3.jpg);\'></a>");
document.writeln("									</li>");
document.writeln("									<li><a href=\'#\' class=\'img\' style=\'background-image: url(../../images/image_4.jpg);\'></a>");
document.writeln("									</li>");
document.writeln("									<li><a href=\'#\' class=\'img\' style=\'background-image: url(../../images/image_5.jpg);\'></a>");
document.writeln("									</li>");
document.writeln("									<li><a href=\'#\' class=\'img\' style=\'background-image: url(../../images/image_6.jpg);\'></a>");
document.writeln("									</li>");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'col-md\'>");
document.writeln("							<div class=\'ftco-footer-widget mb-4\'>");
document.writeln("								<h2 class=\'ftco-heading-2\'>Archives</h2>");
document.writeln("								<ul class=\'list-unstyled categories\'>");
document.writeln("									<li><a href=\'#\'>November 2018 <span>(105)</span></a></li>");
document.writeln("									<li><a href=\'#\'>October 2018 <span>(212)</span></a></li>");
document.writeln("									<li><a href=\'#\'>September 2018 <span>(150)</span></a></li>");
document.writeln("									<li><a href=\'#\'>August 2018 <span>(100)</span></a></li>");
document.writeln("									<li><a href=\'#\'>July 2018 <span>(200)</span></a></li>");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("						<div class=\'col-md\'>");
document.writeln("							<div class=\'ftco-footer-widget mb-4\'>");
document.writeln("								<h2 class=\'ftco-heading-2\'>Have a Questions?</h2>");
document.writeln("								<div class=\'block-23 mb-3\'>");
document.writeln("									<ul>");
document.writeln("										<li><span class=\'icon icon-map-marker\'></span><span class=\'text\'>203 Fake St.");
document.writeln("												Mountain View, San Francisco, California, USA</span></li>");
document.writeln("										<li><a href=\'#\'><span class=\'icon icon-phone\'></span><span class=\'text\'>+2 392");
document.writeln("													3929 210</span></a></li>");
document.writeln("										<li><a href=\'#\'><span class=\'icon icon-envelope\'></span><span");
document.writeln("													class=\'text\'>info@yourdomain.com</span></a></li>");
document.writeln("									</ul>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'row\'>");
document.writeln("						<div class=\'col-md-12\'>");
document.writeln("");
document.writeln("							<p><!-- Link back to Colorlib can\'t be removed. Template is licensed under CC BY 3.0. -->");
document.writeln("								Copyright &copy;");
document.writeln("								<script>document.write(new Date().getFullYear());</script> All rights reserved | This");
document.writeln("								template is made with <i class=\'icon-heart\' aria-hidden=\'true\'></i> by <a");
document.writeln("									href=\'https://colorlib.com\' target=\'_blank\'>Colorlib</a>");
document.writeln("								<!-- Link back to Colorlib can\'t be removed. Template is licensed under CC BY 3.0. -->");
document.writeln("							</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</footer>");