document.writeln("						<div class=\'col-lg-4 sidebar ftco-animate bg-light\'>");
document.writeln("							<div class=\'sidebar-box\'>");
document.writeln("								<form action=\'#\' class=\'search-form\'>");
document.writeln("									<div class=\'form-group\'>");
document.writeln("										<span class=\'icon icon-search\'></span>");
document.writeln("										<input type=\'text\' class=\'form-control\'");
document.writeln("											placeholder=\'Type a keyword and hit enter\'>");
document.writeln("									</div>");
document.writeln("								</form>");
document.writeln("							</div>");
document.writeln("							<div class=\'sidebar-box ftco-animate\'>");
document.writeln("								<h3 class=\'sidebar-heading\'>Categories</h3>");
document.writeln("								<ul class=\'categories\'>");
document.writeln("									<li><a href=\'#\'>Fashion <span>(6)</span></a></li>");
document.writeln("									<li><a href=\'#\'>Technology <span>(8)</span></a></li>");
document.writeln("									<li><a href=\'#\'>Travel <span>(2)</span></a></li>");
document.writeln("									<li><a href=\'#\'>Food <span>(2)</span></a></li>");
document.writeln("									<li><a href=\'#\'>Photography <span>(7)</span></a></li>");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("");
document.writeln("							<div class=\'sidebar-box ftco-animate\'>");
document.writeln("								<h3 class=\'sidebar-heading\'>Popular Articles</h3>");
document.writeln("								<div class=\'block-21 mb-4 d-flex\'>");
document.writeln("									<a class=\'blog-img mr-4\' style=\'background-image: url(../../images/image_1.jpg);\'></a>");
document.writeln("									<div class=\'text\'>");
document.writeln("										<h3 class=\'heading\'><a href=\'#\'>Even the all-powerful Pointing has no");
document.writeln("												control</a></h3>");
document.writeln("										<div class=\'meta\'>");
document.writeln("											<div><a href=\'#\'><span class=\'icon-calendar\'></span> Oct. 04, 2018</a></div>");
document.writeln("											<div><a href=\'#\'><span class=\'icon-person\'></span> Dave Lewis</a></div>");
document.writeln("											<div><a href=\'#\'><span class=\'icon-chat\'></span> 19</a></div>");
document.writeln("										</div>");
document.writeln("									</div>");
document.writeln("								</div>");
document.writeln("								<div class=\'block-21 mb-4 d-flex\'>");
document.writeln("									<a class=\'blog-img mr-4\' style=\'background-image: url(../../images/image_2.jpg);\'></a>");
document.writeln("									<div class=\'text\'>");
document.writeln("										<h3 class=\'heading\'><a href=\'#\'>Even the all-powerful Pointing has no");
document.writeln("												control</a></h3>");
document.writeln("										<div class=\'meta\'>");
document.writeln("											<div><a href=\'#\'><span class=\'icon-calendar\'></span> Oct. 04, 2018</a></div>");
document.writeln("											<div><a href=\'#\'><span class=\'icon-person\'></span> Dave Lewis</a></div>");
document.writeln("											<div><a href=\'#\'><span class=\'icon-chat\'></span> 19</a></div>");
document.writeln("										</div>");
document.writeln("									</div>");
document.writeln("								</div>");
document.writeln("								<div class=\'block-21 mb-4 d-flex\'>");
document.writeln("									<a class=\'blog-img mr-4\' style=\'background-image: url(../../images/image_3.jpg);\'></a>");
document.writeln("									<div class=\'text\'>");
document.writeln("										<h3 class=\'heading\'><a href=\'#\'>Even the all-powerful Pointing has no");
document.writeln("												control</a></h3>");
document.writeln("										<div class=\'meta\'>");
document.writeln("											<div><a href=\'#\'><span class=\'icon-calendar\'></span> Oct. 04, 2018</a></div>");
document.writeln("											<div><a href=\'#\'><span class=\'icon-person\'></span> Dave Lewis</a></div>");
document.writeln("											<div><a href=\'#\'><span class=\'icon-chat\'></span> 19</a></div>");
document.writeln("										</div>");
document.writeln("									</div>");
document.writeln("								</div>");
document.writeln("							</div>");
document.writeln("");
document.writeln("							<div class=\'sidebar-box ftco-animate\'>");
document.writeln("								<h3 class=\'sidebar-heading\'>Tag Cloud</h3>");
document.writeln("								<ul class=\'tagcloud\'>");
document.writeln("									<a href=\'#\' class=\'tag-cloud-link\'>animals</a>");
document.writeln("									<a href=\'#\' class=\'tag-cloud-link\'>human</a>");
document.writeln("									<a href=\'#\' class=\'tag-cloud-link\'>people</a>");
document.writeln("									<a href=\'#\' class=\'tag-cloud-link\'>cat</a>");
document.writeln("									<a href=\'#\' class=\'tag-cloud-link\'>dog</a>");
document.writeln("									<a href=\'#\' class=\'tag-cloud-link\'>nature</a>");
document.writeln("									<a href=\'#\' class=\'tag-cloud-link\'>leaves</a>");
document.writeln("									<a href=\'#\' class=\'tag-cloud-link\'>food</a>");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("");
document.writeln("							<div class=\'sidebar-box subs-wrap img\' style=\'background-image: url(../../images/bg_1.jpg);\'>");
document.writeln("								<div class=\'overlay\'></div>");
document.writeln("								<h3 class=\'mb-4 sidebar-heading\'>Newsletter</h3>");
document.writeln("								<p class=\'mb-4\'>Far far away, behind the word mountains, far from the countries Vokalia");
document.writeln("								</p>");
document.writeln("								<form action=\'#\' class=\'subscribe-form\'>");
document.writeln("									<div class=\'form-group\'>");
document.writeln("										<input type=\'text\' class=\'form-control\' placeholder=\'Email Address\'>");
document.writeln("										<input type=\'submit\' value=\'Subscribe\' class=\'mt-2 btn btn-white submit\'>");
document.writeln("									</div>");
document.writeln("								</form>");
document.writeln("							</div>");
document.writeln("");
document.writeln("							<div class=\'sidebar-box ftco-animate\'>");
document.writeln("								<h3 class=\'sidebar-heading\'>Archives</h3>");
document.writeln("								<ul class=\'categories\'>");
document.writeln("									<li><a href=\'#\'>October 2018 <span>(10)</span></a></li>");
document.writeln("									<li><a href=\'#\'>September 2018 <span>(6)</span></a></li>");
document.writeln("									<li><a href=\'#\'>August 2018 <span>(8)</span></a></li>");
document.writeln("									<li><a href=\'#\'>July 2018 <span>(2)</span></a></li>");
document.writeln("									<li><a href=\'#\'>June 2018 <span>(7)</span></a></li>");
document.writeln("									<li><a href=\'#\'>May 2018 <span>(5)</span></a></li>");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("");
document.writeln("");
document.writeln("							<div class=\'sidebar-box ftco-animate\'>");
document.writeln("								<h3 class=\'sidebar-heading\'>Paragraph</h3>");
document.writeln("								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem");
document.writeln("									necessitatibus voluptate quod mollitia delectus aut.</p>");
document.writeln("							</div>");
document.writeln("						</div><!-- END COL -->");